server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: cicero
    password: 123456
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    port: 465
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: group11_cinema@163.com
    #授权码
    password: CPSGBCWVASIPWRNP
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mov.entity
  configuration:
    map-underscore-to-camel-case: true
    # mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# CPSGBCWVASIPWRNP